# Site
repository: Lone5267/lone5267.github.io
favicon: images/favicon.ico

# Personal info
name: Ming Liu
title: A postgraduate Student
#mobile: +44 07873800701 / +86 13015503626
email: Mliu54@sheffield.ac.uk
website: www.github.com/lone5267
#address: 212-H, UNINN BaileyStreet, 39 BaileyStreet, Sheffield, UK / No.101, Building 21, Haida Community,
#  Hefei City, Anhui Province, China

# Social links
#twitter_username:
github_username:  lone5267
# dribbble_username: jekyll
facebook_username: nvpiao
# flickr_username: jekyll
instagram_username: nvpiao
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/myself_crop.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ming Liu and I'm a postgraduate at the [Department of Computer Science](https://www.sheffield.ac.uk/dcs    "Department of Computer Science"), the [University of Sheffiled](https://www.sheffield.ac.uk/ "University of Sheffield").
  My major is Computer Science With Speech and Language Processing. I am now really interested in Natural Language Processing (NLP) and machine learning.

  Additionally, I Completed my BSc [Software Engineering](http://international.zzu.edu.cn/en/admission/detail?cid=17&pid=12&spid=4&detail=615 "Software Engineering"), [ZHENGZHOU UNIVERSITY](http://international.zzu.edu.cn/en/index    "ZHENGZHOU UNIVERSITY").
  After graduation, I worked for two years as a Backend development engineer.

# Projects Section
projects_title: ""

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: Lone5267/lone5267.github.io

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

darkmode: false
